/** Noms des collections, en un seul endroit : plus de chaînes magiques. */
export const C = {
  users: "users",
  currencies: "currencies",
  exchangeRates: "exchange_rates",
  jurisdictions: "jurisdictions",
  settings: "settings",
  owners: "owners",
  tenants: "tenants",
  guarantors: "guarantors",
  contractors: "contractors",
  portfolios: "portfolios",
  properties: "properties",
  buildings: "buildings",
  units: "units",
  applications: "applications",
  visits: "visits",
  leases: "leases",
  leaseAmendments: "lease_amendments",
  leaseEvents: "lease_events",
  rentSchedules: "rent_schedules",
  invoices: "invoices",
  invoiceItems: "invoice_items",
  charges: "charges",
  payments: "payments",
  paymentProofs: "payment_proofs",
  balances: "balances",
  reminders: "reminders",
  reminderAttempts: "reminder_attempts",
  promises: "promises_to_pay",
  notices: "notices",
  inspections: "inspections",
  inspectionItems: "inspection_items",
  deposits: "deposits",
  depositTransactions: "deposit_transactions",
  tickets: "maintenance_tickets",
  maintenanceTasks: "maintenance_tasks",
  expenses: "expenses",
  ownerStatements: "owner_statements",
  documents: "documents",
  templates: "communication_templates",
  messages: "messages",
  notifications: "notifications",
  tasks: "tasks",
  appointments: "appointments",
  automationRules: "automation_rules",
  auditLogs: "audit_logs",
  backups: "backups",
};

/** Collections dont la suppression passe par la corbeille (§57). */
export const SOFT_DELETABLE = [
  C.owners, C.tenants, C.guarantors, C.contractors, C.portfolios,
  C.properties, C.buildings, C.units, C.applications, C.visits,
  C.leases, C.leaseAmendments, C.invoices, C.charges, C.payments,
  C.reminders, C.tickets, C.expenses, C.documents, C.tasks,
];

/** Collections dont toute écriture est marquée « financière » dans l'audit (§4). */
export const FINANCIAL = [
  C.payments, C.invoices, C.invoiceItems, C.charges, C.leases,
  C.deposits, C.depositTransactions, C.expenses, C.ownerStatements,
  C.rentSchedules, C.balances,
];
